project_name: pico
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "SNAPSHOT-{{ .ShortCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - image_templates:
      - picostack/pico:{{ .Tag }}
      - picostack/pico:v{{ .Major }}
      - picostack/pico:v{{ .Major }}.{{ .Minor }}
      - picostack/pico:{{ .ShortCommit }}
      - picostack/pico:latest
nfpms:
  - vendor: Southclaws
    homepage: https://github.com/picostack/pico
    maintainer: Southclaws <hello@southcla.ws>
    description: |
      A docker-compose application manager that deploys and maintains a set of
      compose projects and provides secret management for them via Vault.
    license: GPLv3
    formats:
      - deb
      # - rpm
