name: Stage

on:
  push:
    branches: [staging]

jobs:
  stage:
    name: stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14.1
      - uses: actions/checkout@v2
      - run: go get -v -t -d

      - name: Test
        run: go test -v ./...

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Staging
        run: go build -ldflags="-w -s"
        env:
          CGO_ENABLED: "0"
          GOOS: linux
          GOARCH: amd64

      - name: Publish
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: picostack/pico
          tags: staging
          tag_with_sha: true
